apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../releases/v2.5.11
  - ../../common
  - ../../repos
  - ../../apps

namespace: argocd

commonLabels:
    app.kubernetes.io/instance: argocd