apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: default
  source:
    path: web
    repoURL: https://github.com/fabianmet/cooking-with-edge.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true